baseURL = "https://yyds1w3.github.io/"
languageCode = "en-us"  # 关键点：这里改成美式英语
title = "Travel"    # 标题也改成英文

theme = "PaperMod"

[params]
    defaultTheme = "auto"
    ShowCodeCopyButtons = true
    ShowShareButtons = false
    
    # --- 首页个人简介 (英文) ---
    [params.profileMode]
    enabled = true
    title = "Hello, I'm Coder"
    subtitle = "Algorithms / C++ / Linux Enthusiast" # 副标题改成英文
    imageUrl = "https://codeforces.com/userpic.codeforces.org/4525726/title/6166efe220e3483b.jpg" 

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yyds1w3"

# --- 顶栏菜单 (英文) ---
[[menu.main]]
    name = "Posts"    # 文章 -> Posts
    url = "/posts"
    weight = 1
[[menu.main]]
    name = "Search"   # 搜索 -> Search
    url = "/search"
    weight = 2
[[menu.main]]
    name = "About"    # 关于我 -> About
    url = "/about"
    weight = 3

# --- 代码高亮保持不变 ---
[markup]
    [markup.highlight]
        noClasses = false
        anchorLineNos = true
        codeFences = true
        guessSyntax = true
        lineNos = true
        style = "monokai"

[outputs]
    home = ["HTML", "RSS", "JSON"] # 这一行最重要，开启 JSON 输出